// Copyright (c) 2026 Reactor Technologies, Inc. All rights reserved.

// Auto-generated by @reactor-team/codegen — DO NOT EDIT
// Model: echo-wm-flash v0.1.0

"use client";

import { type ReactElement } from "react";
import {
  ReactorProvider,
  useReactor,
  useReactorMessage,
  ReactorView,
  type ReactorViewProps,
} from "@reactor-team/js-sdk";
import {
  MODEL_NAME,
  EchoWmFlashTracks,
  type EchoWmFlashOptions,
  type EchoWmFlashSetImageParams,
  type EchoWmFlashSetPromptParams,
  type EchoWmFlashSetCameraMotionParams,
  type EchoWmFlashSetFovParams,
  type EchoWmFlashResetParams,
  type EchoWmFlashMessage,
  type EchoWmFlashStateUpdateMessage,
  type EchoWmFlashImageSelectedMessage,
  type EchoWmFlashPromptQueuedMessage,
  type EchoWmFlashCameraMotionChangedMessage,
  type EchoWmFlashRolloutResetQueuedMessage,
  type EchoWmFlashChunkCompletedMessage,
  type EchoWmFlashAutomaticResetQueuedMessage,
  type EchoWmFlashRecvTrackName,
} from "./client";

/**
 * @internal Flatten the `{ type, data, uploads? }` envelope the SDK
 * hands to `reactor.on("message", …)` so a field the model schema
 * declares on a message is reachable at `msg.<field>` — matching the
 * shape the exported message interfaces promise.
 */
function _unwrapMessage<T>(raw: unknown): T {
  const env = raw as { type?: string; data?: Record<string, unknown> };
  if (
    env &&
    typeof env === "object" &&
    env.data &&
    typeof env.data === "object"
  ) {
    return { ...env.data, type: env.type } as T;
  }
  return raw as T;
}

/**
 * Props for the {@link EchoWmFlashProvider} component.
 *
 * Derived from `ReactorProvider`'s own props, with `modelName` and
 * `modelTracks` stripped — those are supplied by this provider.
 */
export type EchoWmFlashProviderProps = Omit<
  Parameters<typeof ReactorProvider>[0],
  "modelName" | "modelTracks"
>;

/**
 * Provider for the EchoWmFlash model.
 *
 * Wraps {@link ReactorProvider} with `modelName` and `modelTracks` pre-configured from the
 * generated constants. Drop this near the top of your tree, then use
 * {@link useEchoWmFlash} and the `useEchoWmFlash<Message>` hooks below it.
 */
export function EchoWmFlashProvider({
  children,
  ...rest
}: EchoWmFlashProviderProps): ReactElement {
  return (
    <ReactorProvider
      {...rest}
      modelName={MODEL_NAME}
      modelTracks={[...EchoWmFlashTracks]}
    >
      {children}
    </ReactorProvider>
  );
}

/**
 * Access the EchoWmFlash model as typed commands bound to the nearest
 * {@link EchoWmFlashProvider}.
 *
 * Returns the full action surface — every public field on the SDK's
 * `ReactorStore` (`status`, `sessionId`, `connect`, `disconnect`,
 * `sendCommand`, `uploadFile`, `publish`, `unpublish`, `reconnect`,
 * …) is exposed automatically, alongside one typed method per
 * model event.
 *
 * Fields are pulled off the store one at a time so Zustand's
 * shallow-equality selector keeps each subscription scoped — a
 * component reading only `status` doesn't re-render when
 * `lastError` changes. Future SDK releases that add new
 * store fields flow into this hook on the next codegen run with no
 * hand-edit (the field list is derived from `js-sdk`'s d.ts via
 * `loadReactorStoreFieldsFromDts` in `sdk-surface.ts`).
 *
 * Each typed event method resolves with the command's correlated
 * reply: the declared reply message for commands that return one,
 * `undefined` once the handler completes for commands that don't.
 */
export function useEchoWmFlash() {
  const connect = useReactor((s) => s.connect);
  const connectOptions = useReactor((s) => s.connectOptions);
  const disconnect = useReactor((s) => s.disconnect);
  const downloadClipAsFile = useReactor((s) => s.downloadClipAsFile);
  const jwtToken = useReactor((s) => s.jwtToken);
  const lastError = useReactor((s) => s.lastError);
  const lastMessage = useReactor((s) => s.lastMessage);
  const pauseTrack = useReactor((s) => s.pauseTrack);
  const publish = useReactor((s) => s.publish);
  const reconnect = useReactor((s) => s.reconnect);
  const requestClip = useReactor((s) => s.requestClip);
  const requestRecording = useReactor((s) => s.requestRecording);
  const resumeTrack = useReactor((s) => s.resumeTrack);
  const sendCommand = useReactor((s) => s.sendCommand);
  const sessionId = useReactor((s) => s.sessionId);
  const status = useReactor((s) => s.status);
  const tracks = useReactor((s) => s.tracks);
  const unpublish = useReactor((s) => s.unpublish);
  const uploadFile = useReactor((s) => s.uploadFile);

  return {
    connect,
    connectOptions,
    disconnect,
    downloadClipAsFile,
    jwtToken,
    lastError,
    lastMessage,
    pauseTrack,
    publish,
    reconnect,
    requestClip,
    requestRecording,
    resumeTrack,
    sendCommand,
    sessionId,
    status,
    tracks,
    unpublish,
    uploadFile,
    setImage: async (params: EchoWmFlashSetImageParams): Promise<EchoWmFlashImageSelectedMessage | undefined> => {
      const reply = await sendCommand("set_image", params);
      return reply === undefined ? undefined : _unwrapMessage<EchoWmFlashImageSelectedMessage>(reply);
    },
    randomImage: async (): Promise<EchoWmFlashImageSelectedMessage | undefined> => {
      const reply = await sendCommand("random_image", {});
      return reply === undefined ? undefined : _unwrapMessage<EchoWmFlashImageSelectedMessage>(reply);
    },
    setPrompt: async (params: EchoWmFlashSetPromptParams): Promise<EchoWmFlashPromptQueuedMessage | undefined> => {
      const reply = await sendCommand("set_prompt", params);
      return reply === undefined ? undefined : _unwrapMessage<EchoWmFlashPromptQueuedMessage>(reply);
    },
    setCameraMotion: async (params: EchoWmFlashSetCameraMotionParams): Promise<EchoWmFlashCameraMotionChangedMessage | undefined> => {
      const reply = await sendCommand("set_camera_motion", params);
      return reply === undefined ? undefined : _unwrapMessage<EchoWmFlashCameraMotionChangedMessage>(reply);
    },
    releaseCamera: async (): Promise<EchoWmFlashCameraMotionChangedMessage | undefined> => {
      const reply = await sendCommand("release_camera", {});
      return reply === undefined ? undefined : _unwrapMessage<EchoWmFlashCameraMotionChangedMessage>(reply);
    },
    setFov: async (params: EchoWmFlashSetFovParams): Promise<EchoWmFlashCameraMotionChangedMessage | undefined> => {
      const reply = await sendCommand("set_fov", params);
      return reply === undefined ? undefined : _unwrapMessage<EchoWmFlashCameraMotionChangedMessage>(reply);
    },
    reset: async (params: EchoWmFlashResetParams): Promise<EchoWmFlashRolloutResetQueuedMessage | undefined> => {
      const reply = await sendCommand("reset", params);
      return reply === undefined ? undefined : _unwrapMessage<EchoWmFlashRolloutResetQueuedMessage>(reply);
    },
  };
}

/**
 * Subscribe to any EchoWmFlash message with a fully-typed handler.
 * The handler receives a discriminated EchoWmFlashMessage.
 */
export function useEchoWmFlashMessage(
  handler: (message: EchoWmFlashMessage) => void,
): void {
  useReactorMessage((msg: unknown) =>
    handler(_unwrapMessage<EchoWmFlashMessage>(msg)),
  );
}

/**
 * Subscribe to "state_update" messages only.
 * Handler receives a fully-typed EchoWmFlashStateUpdateMessage.
 */
export function useEchoWmFlashStateUpdate(
  handler: (message: EchoWmFlashStateUpdateMessage) => void,
): void {
  useReactorMessage((msg: unknown) => {
    const m = _unwrapMessage<EchoWmFlashMessage>(msg);
    if (m.type === "state_update") {
      handler(m as EchoWmFlashStateUpdateMessage);
    }
  });
}

/**
 * Subscribe to "image_selected" messages only.
 * Handler receives a fully-typed EchoWmFlashImageSelectedMessage.
 */
export function useEchoWmFlashImageSelected(
  handler: (message: EchoWmFlashImageSelectedMessage) => void,
): void {
  useReactorMessage((msg: unknown) => {
    const m = _unwrapMessage<EchoWmFlashMessage>(msg);
    if (m.type === "image_selected") {
      handler(m as EchoWmFlashImageSelectedMessage);
    }
  });
}

/**
 * Subscribe to "prompt_queued" messages only.
 * Handler receives a fully-typed EchoWmFlashPromptQueuedMessage.
 */
export function useEchoWmFlashPromptQueued(
  handler: (message: EchoWmFlashPromptQueuedMessage) => void,
): void {
  useReactorMessage((msg: unknown) => {
    const m = _unwrapMessage<EchoWmFlashMessage>(msg);
    if (m.type === "prompt_queued") {
      handler(m as EchoWmFlashPromptQueuedMessage);
    }
  });
}

/**
 * Subscribe to "camera_motion_changed" messages only.
 * Handler receives a fully-typed EchoWmFlashCameraMotionChangedMessage.
 */
export function useEchoWmFlashCameraMotionChanged(
  handler: (message: EchoWmFlashCameraMotionChangedMessage) => void,
): void {
  useReactorMessage((msg: unknown) => {
    const m = _unwrapMessage<EchoWmFlashMessage>(msg);
    if (m.type === "camera_motion_changed") {
      handler(m as EchoWmFlashCameraMotionChangedMessage);
    }
  });
}

/**
 * Subscribe to "rollout_reset_queued" messages only.
 * Handler receives a fully-typed EchoWmFlashRolloutResetQueuedMessage.
 */
export function useEchoWmFlashRolloutResetQueued(
  handler: (message: EchoWmFlashRolloutResetQueuedMessage) => void,
): void {
  useReactorMessage((msg: unknown) => {
    const m = _unwrapMessage<EchoWmFlashMessage>(msg);
    if (m.type === "rollout_reset_queued") {
      handler(m as EchoWmFlashRolloutResetQueuedMessage);
    }
  });
}

/**
 * Subscribe to "chunk_completed" messages only.
 * Handler receives a fully-typed EchoWmFlashChunkCompletedMessage.
 */
export function useEchoWmFlashChunkCompleted(
  handler: (message: EchoWmFlashChunkCompletedMessage) => void,
): void {
  useReactorMessage((msg: unknown) => {
    const m = _unwrapMessage<EchoWmFlashMessage>(msg);
    if (m.type === "chunk_completed") {
      handler(m as EchoWmFlashChunkCompletedMessage);
    }
  });
}

/**
 * Subscribe to "automatic_reset_queued" messages only.
 * Handler receives a fully-typed EchoWmFlashAutomaticResetQueuedMessage.
 */
export function useEchoWmFlashAutomaticResetQueued(
  handler: (message: EchoWmFlashAutomaticResetQueuedMessage) => void,
): void {
  useReactorMessage((msg: unknown) => {
    const m = _unwrapMessage<EchoWmFlashMessage>(msg);
    if (m.type === "automatic_reset_queued") {
      handler(m as EchoWmFlashAutomaticResetQueuedMessage);
    }
  });
}

/**
 * Subscribe to a recvonly MediaStreamTrack the model publishes, by name.
 *
 * Returns `undefined` until the model emits the track, then the live track for the lifetime of the connection. `name` is constrained to the model's declared recvonly channels — use one of `EchoWmFlashRecvTrackName`.
 * @param name - A recvonly track name declared by the model
 * @returns The live MediaStreamTrack, or `undefined` until received
 */
export function useEchoWmFlashTrack(
  name: EchoWmFlashRecvTrackName,
): MediaStreamTrack | undefined {
  return useReactor((s) => s.tracks[name]);
}

export type EchoWmFlashMainVideoViewProps = Omit<ReactorViewProps, "track">;

/**
 * Render the model's "main_video" recvonly video track in a `<video>` element.
 *
 * Thin wrapper around `<ReactorView>` with `track` pre-bound. Accepts every other `ReactorViewProps` (`audioTrack`, `className`, `style`, `videoObjectFit`, `muted`, …). Must be rendered inside `<EchoWmFlashProvider>`.
 */
export function EchoWmFlashMainVideoView(
  props: EchoWmFlashMainVideoViewProps,
): ReactElement {
  return <ReactorView {...props} track="main_video" />;
}
