// Copyright (c) 2026 Reactor Technologies, Inc. All rights reserved.

// Auto-generated by @reactor-team/codegen — DO NOT EDIT
// Model: echo-wm-flash v0.1.0

import { Reactor, FileRef } from "@reactor-team/js-sdk";
export { FileRef };

export const MODEL_NAME = "echo-wm-flash" as const;
export const MODEL_VERSION = "v0.1.0" as const;

/**
 * Preset media tracks for the EchoWmFlash model.
 *
 * Declared in the model's OpenAPI schema and passed to the SDK as
 * `modelTracks` so the transport can prepare the SDP offer in
 * parallel with session polling (faster first-frame latency).
 */
export const EchoWmFlashTracks = [
  { name: "main_video", kind: "video", direction: "recvonly" },
  { name: "main_audio", kind: "audio", direction: "recvonly" },
] as const;

/** Track names the client can subscribe to (recvonly, from the client's perspective). */
export type EchoWmFlashRecvTrackName =
  "main_video"
  | "main_audio";

/** Select an uploaded first frame and start a fresh audiovisual world with continuous generation. Supply a prompt or leave it blank to use the configured image-neutral default. Emits `image_selected` and broadcasts `state_update` on success, or `command_error` when the upload is invalid. */
export interface EchoWmFlashSetImageParams {
  /** Reference to a file uploaded via the Reactor upload protocol. */

  image: FileRef;
  /**
   * Scene, motion, sound, music, and speech description. An empty value uses the configured image-neutral default for the new scene.
   * @maxLength 4096
   * @default ""
   */

  prompt?: string;
  /**
   * Fresh-rollout seed, or -1 to retain the active seed.
   * @minimum -1
   * @maximum 2147483647
   * @default -1
   */

  seed?: number;
}

/** Replace the text condition and queue a fresh rollout from the selected image. The new prompt begins at chunk one and continuous generation resumes from the fresh world. Emits `prompt_queued` and broadcasts `state_update` on success, or `command_error` before image selection or for empty text. */
export interface EchoWmFlashSetPromptParams {
  /**
   * Non-empty scene, character, perspective, sound, music, and speech description.
   * @maxLength 4096
   * @default ""
   */

  prompt?: string;
}

/** Set Echo-WM's four native held camera axes atomically. Values are sampled at the next chunk boundary and remain active until changed or released. Emits `camera_motion_changed` and broadcasts `state_update` on success, or `command_error` before image selection. */
export interface EchoWmFlashSetCameraMotionParams {
  /**
   * Backward (-1) to forward (1); zero is neutral.
   * @minimum -1
   * @maximum 1
   * @default 0
   */

  forward?: number;
  /**
   * Left (-1) to right (1); zero is neutral.
   * @minimum -1
   * @maximum 1
   * @default 0
   */

  strafe?: number;
  /**
   * Look down (-1) to up (1); zero is neutral.
   * @minimum -1
   * @maximum 1
   * @default 0
   */

  pitch?: number;
  /**
   * Turn left (-1) to right (1); zero is neutral.
   * @minimum -1
   * @maximum 1
   * @default 0
   */

  yaw?: number;
}

/** Set the horizontal camera field of view for forthcoming chunks. The value is sampled at the next chunk boundary and remains active. Emits `camera_motion_changed` and broadcasts `state_update` on success, or `command_error` before image selection. */
export interface EchoWmFlashSetFovParams {
  /**
   * Horizontal field of view in degrees from 30 through 120.
   * @minimum 30
   * @maximum 120
   * @default 70
   */

  fov_degrees?: number;
}

/** Queue a fresh bounded rollout from the selected image and current prompt. The command releases camera motion and continues generation from chunk one. Emits `rollout_reset_queued` and broadcasts `state_update` on success, or `command_error` before image selection. */
export interface EchoWmFlashResetParams {
  /**
   * Fresh-rollout seed, or -1 to retain the active seed.
   * @minimum -1
   * @maximum 2147483647
   * @default -1
   */

  seed?: number;
}

/** Emitted after connection, state mutation, reset, or chunk completion. */
export interface EchoWmFlashStateUpdateMessage {
  type: "state_update";
  /** Source of the first frame: "uploaded", "built_in", or null before an image is selected. */

  image_source: "uploaded" | "built_in" | null;
  /** Selected first-frame filename, or null before image selection. */

  image_name: string | null;
  /** Prompt for the current or queued world, or null before image selection. */

  prompt: string | null;
  /** Prompt used by the latest completed chunk, or null before generation. */

  active_prompt: string | null;
  /** Random seed for the current or queued world. */

  seed: number;
  /** Whether a fresh world will be initialized before the next chunk. */

  reset_queued: boolean;
  /** Whether image preparation or one audio-video chunk is in progress. */

  generating: boolean;
  /** Completed audio-video chunks since the latest world reset. */

  completed_chunks: number;
  /** One-based chunk that accepted camera state will first affect. */

  next_chunk: number | null;
  /** Chunk count that automatically starts a fresh world from the same image. */

  max_chunks: number;
  /** Active backward-to-forward camera motion. */

  forward: number;
  /** Active left-to-right camera motion. */

  strafe: number;
  /** Active downward-to-upward pitch motion. */

  pitch: number;
  /** Active left-to-right yaw motion. */

  yaw: number;
  /** Active horizontal field of view in degrees. */

  fov_degrees: number;
}

/** Emitted when an uploaded or built-in image queues a fresh world. */
export interface EchoWmFlashImageSelectedMessage {
  type: "image_selected";
  /** Image source accepted by the command. */

  source: "uploaded" | "built_in";
  /** Selected first-frame filename. */

  filename: string;
  /** Non-empty prompt for the fresh world. */

  prompt: string;
  /** Random seed for the fresh world. */

  seed: number;
}

/** Emitted when a prompt queues a fresh world from the selected image. */
export interface EchoWmFlashPromptQueuedMessage {
  type: "prompt_queued";
  /** Trimmed prompt accepted by `set_prompt`. */

  prompt: string;
  /** One-based chunk affected by the prompt; always 1 after the reset. */

  applies_to_chunk: number;
}

/** Emitted when camera motion or field of view changes. */
export interface EchoWmFlashCameraMotionChangedMessage {
  type: "camera_motion_changed";
  /** Active backward-to-forward motion. */

  forward: number;
  /** Active left-to-right motion. */

  strafe: number;
  /** Active downward-to-upward pitch motion. */

  pitch: number;
  /** Active left-to-right yaw motion. */

  yaw: number;
  /** Active horizontal field of view. */

  fov_degrees: number;
  /** First chunk expected to sample these values, or null without an image. */

  applies_to_chunk: number | null;
}

/** Emitted when `reset` queues a fresh world from the selected image. */
export interface EchoWmFlashRolloutResetQueuedMessage {
  type: "rollout_reset_queued";
  /** Random seed for the fresh world. */

  seed: number;
  /** Completed chunks discarded by the reset. */

  replaced_chunks: number;
}

/** Emitted once after one synchronized audio-video chunk finishes. */
export interface EchoWmFlashChunkCompletedMessage {
  type: "chunk_completed";
  /** One-based chunk that completed. */

  chunk: number;
  /** RGB frames carried by `main_video`. */

  video_frames: number;
  /** 48 kHz mono samples carried by `main_audio`. */

  audio_samples: number;
  /** Wall-clock seconds spent generating and decoding the chunk. */

  generation_seconds: number;
  /** CUDA seconds spent in the four denoising transformer forwards. */

  denoise_seconds: number | null;
  /** CUDA seconds spent committing clean audio-video KV cache entries. */

  cache_commit_seconds: number | null;
  /** CUDA seconds spent decoding the video latent block. */

  video_decode_seconds: number | null;
  /** CUDA seconds spent decoding and vocoding the audio latent block. */

  audio_decode_seconds: number | null;
  /** Total CUDA seconds from denoising through synchronized media decode. */

  cuda_total_seconds: number | null;
  /** Prompt sampled by the completed chunk. */

  prompt: string;
  /** Forward motion sampled by the chunk. */

  forward: number;
  /** Strafe motion sampled by the chunk. */

  strafe: number;
  /** Pitch motion sampled by the chunk. */

  pitch: number;
  /** Yaw motion sampled by the chunk. */

  yaw: number;
}

/** Emitted after the final chunk queues a fresh bounded rollout. */
export interface EchoWmFlashAutomaticResetQueuedMessage {
  type: "automatic_reset_queued";
  /** Chunks completed when the configured bound was reached. */

  completed_chunks: number;
  /** Configured chunk bound that was reached. */

  max_chunks: number;
  /** Seed retained by the queued fresh world. */

  seed: number;
}

export type EchoWmFlashMessage =
  | EchoWmFlashStateUpdateMessage
  | EchoWmFlashImageSelectedMessage
  | EchoWmFlashPromptQueuedMessage
  | EchoWmFlashCameraMotionChangedMessage
  | EchoWmFlashRolloutResetQueuedMessage
  | EchoWmFlashChunkCompletedMessage
  | EchoWmFlashAutomaticResetQueuedMessage;

/**
 * Options for creating a EchoWmFlashModel (model name is set automatically).
 *
 * Derived from `Reactor`'s own constructor options with `modelName`
 * and `modelTracks` removed — those are supplied by this class.
 * Any new option the SDK adds appears here automatically on the
 * next `defaultSdkVersion` bump.
 */
export type EchoWmFlashOptions = Omit<
  ConstructorParameters<typeof Reactor>[0],
  "modelName" | "modelTracks"
>;

/**
 * @internal Flatten the `{ type, data, uploads? }` envelope the SDK
 * hands to `reactor.on("message", …)` so a field the model schema
 * declares on a message is reachable at `msg.<field>` — matching the
 * shape the exported message interfaces promise.
 */
function _unwrapMessage<T>(raw: unknown): T {
  const env = raw as { type?: string; data?: Record<string, unknown> };
  if (
    env &&
    typeof env === "object" &&
    env.data &&
    typeof env.data === "object"
  ) {
    return { ...env.data, type: env.type } as T;
  }
  return raw as T;
}

/**
 * Strongly-typed client for the EchoWmFlash model.
 *
 * Extends {@link Reactor} with the model name (and modelTracks) baked into the
 * constructor, so every public method on Reactor — `connect`, `disconnect`,
 * `sendCommand`, `on`/`off`, `getStats`, `publishTrack`/`unpublishTrack`,
 * etc. — is reachable directly on the instance. The schema-derived sugar
 * below adds typed wrappers for every declared event, message, and track.
 */

export class EchoWmFlashModel extends Reactor {
  constructor(options?: EchoWmFlashOptions) {
    super({
      ...options,
      modelName: MODEL_NAME,
      modelTracks: [...EchoWmFlashTracks],
    });
  }

  /** @deprecated The model client now extends `Reactor` directly — call methods on `this` instead. This accessor returns `this` for backwards compatibility and will be removed in a future major release. */

  get reactor(): this {
    return this;
  }

  /**
   * Select an uploaded first frame and start a fresh audiovisual world with continuous generation. Supply a prompt or leave it blank to use the configured image-neutral default. Emits `image_selected` and broadcasts `state_update` on success, or `command_error` when the upload is invalid.
   * @param params - Select an uploaded first frame and start a fresh audiovisual world with continuous generation. Supply a prompt or leave it blank to use the configured image-neutral default. Emits `image_selected` and broadcasts `state_update` on success, or `command_error` when the upload is invalid.
   * @returns The correlated {@link EchoWmFlashImageSelectedMessage} reply, or `undefined` when the send fails (the SDK never rejects — see `getLastError()`).
   */

  async setImage(params: EchoWmFlashSetImageParams): Promise<EchoWmFlashImageSelectedMessage | undefined> {
    const reply = await this.sendCommand("set_image", params);
    return reply === undefined ? undefined : _unwrapMessage<EchoWmFlashImageSelectedMessage>(reply);
  }

  /**
   * Select a different public Echo-WM example with its matching prompt, field of view, and seed, then start continuous generation from it. Emits `image_selected` and broadcasts `state_update` on success, or `command_error` when no example is configured.
   * @returns The correlated {@link EchoWmFlashImageSelectedMessage} reply, or `undefined` when the send fails (the SDK never rejects — see `getLastError()`).
   */

  async randomImage(): Promise<EchoWmFlashImageSelectedMessage | undefined> {
    const reply = await this.sendCommand("random_image", {});
    return reply === undefined ? undefined : _unwrapMessage<EchoWmFlashImageSelectedMessage>(reply);
  }

  /**
   * Replace the text condition and queue a fresh rollout from the selected image. The new prompt begins at chunk one and continuous generation resumes from the fresh world. Emits `prompt_queued` and broadcasts `state_update` on success, or `command_error` before image selection or for empty text.
   * @param params - Replace the text condition and queue a fresh rollout from the selected image. The new prompt begins at chunk one and continuous generation resumes from the fresh world. Emits `prompt_queued` and broadcasts `state_update` on success, or `command_error` before image selection or for empty text.
   * @returns The correlated {@link EchoWmFlashPromptQueuedMessage} reply, or `undefined` when the send fails (the SDK never rejects — see `getLastError()`).
   */

  async setPrompt(params: EchoWmFlashSetPromptParams): Promise<EchoWmFlashPromptQueuedMessage | undefined> {
    const reply = await this.sendCommand("set_prompt", params);
    return reply === undefined ? undefined : _unwrapMessage<EchoWmFlashPromptQueuedMessage>(reply);
  }

  /**
   * Set Echo-WM's four native held camera axes atomically. Values are sampled at the next chunk boundary and remain active until changed or released. Emits `camera_motion_changed` and broadcasts `state_update` on success, or `command_error` before image selection.
   * @param params - Set Echo-WM's four native held camera axes atomically. Values are sampled at the next chunk boundary and remain active until changed or released. Emits `camera_motion_changed` and broadcasts `state_update` on success, or `command_error` before image selection.
   * @returns The correlated {@link EchoWmFlashCameraMotionChangedMessage} reply, or `undefined` when the send fails (the SDK never rejects — see `getLastError()`).
   */

  async setCameraMotion(params: EchoWmFlashSetCameraMotionParams): Promise<EchoWmFlashCameraMotionChangedMessage | undefined> {
    const reply = await this.sendCommand("set_camera_motion", params);
    return reply === undefined ? undefined : _unwrapMessage<EchoWmFlashCameraMotionChangedMessage>(reply);
  }

  /**
   * Return every held camera axis to neutral for forthcoming chunks. Emits `camera_motion_changed` and broadcasts `state_update` on success, or `command_error` before image selection.
   * @returns The correlated {@link EchoWmFlashCameraMotionChangedMessage} reply, or `undefined` when the send fails (the SDK never rejects — see `getLastError()`).
   */

  async releaseCamera(): Promise<EchoWmFlashCameraMotionChangedMessage | undefined> {
    const reply = await this.sendCommand("release_camera", {});
    return reply === undefined ? undefined : _unwrapMessage<EchoWmFlashCameraMotionChangedMessage>(reply);
  }

  /**
   * Set the horizontal camera field of view for forthcoming chunks. The value is sampled at the next chunk boundary and remains active. Emits `camera_motion_changed` and broadcasts `state_update` on success, or `command_error` before image selection.
   * @param params - Set the horizontal camera field of view for forthcoming chunks. The value is sampled at the next chunk boundary and remains active. Emits `camera_motion_changed` and broadcasts `state_update` on success, or `command_error` before image selection.
   * @returns The correlated {@link EchoWmFlashCameraMotionChangedMessage} reply, or `undefined` when the send fails (the SDK never rejects — see `getLastError()`).
   */

  async setFov(params: EchoWmFlashSetFovParams): Promise<EchoWmFlashCameraMotionChangedMessage | undefined> {
    const reply = await this.sendCommand("set_fov", params);
    return reply === undefined ? undefined : _unwrapMessage<EchoWmFlashCameraMotionChangedMessage>(reply);
  }

  /**
   * Queue a fresh bounded rollout from the selected image and current prompt. The command releases camera motion and continues generation from chunk one. Emits `rollout_reset_queued` and broadcasts `state_update` on success, or `command_error` before image selection.
   * @param params - Queue a fresh bounded rollout from the selected image and current prompt. The command releases camera motion and continues generation from chunk one. Emits `rollout_reset_queued` and broadcasts `state_update` on success, or `command_error` before image selection.
   * @returns The correlated {@link EchoWmFlashRolloutResetQueuedMessage} reply, or `undefined` when the send fails (the SDK never rejects — see `getLastError()`).
   */

  async reset(params: EchoWmFlashResetParams): Promise<EchoWmFlashRolloutResetQueuedMessage | undefined> {
    const reply = await this.sendCommand("reset", params);
    return reply === undefined ? undefined : _unwrapMessage<EchoWmFlashRolloutResetQueuedMessage>(reply);
  }

  /**
   * Subscribe to typed model messages.
   * @param handler - Called with a discriminated EchoWmFlashMessage
   * @returns Unsubscribe function
   */

  onMessage(handler: (message: EchoWmFlashMessage) => void): () => void {
    const wrappedHandler = (raw: unknown) => {
      handler(_unwrapMessage<EchoWmFlashMessage>(raw));
    };
    this.on("message", wrappedHandler);
    return () => this.off("message", wrappedHandler);
  }

  /**
   * Subscribe to "state_update" messages only.
   * @returns Unsubscribe function
   */

  onStateUpdate(handler: (message: EchoWmFlashStateUpdateMessage) => void): () => void {
    return this.onMessage((msg) => {
      if (msg.type === "state_update") handler(msg as EchoWmFlashStateUpdateMessage);
    });
  }

  /**
   * Subscribe to "image_selected" messages only.
   * @returns Unsubscribe function
   */

  onImageSelected(handler: (message: EchoWmFlashImageSelectedMessage) => void): () => void {
    return this.onMessage((msg) => {
      if (msg.type === "image_selected") handler(msg as EchoWmFlashImageSelectedMessage);
    });
  }

  /**
   * Subscribe to "prompt_queued" messages only.
   * @returns Unsubscribe function
   */

  onPromptQueued(handler: (message: EchoWmFlashPromptQueuedMessage) => void): () => void {
    return this.onMessage((msg) => {
      if (msg.type === "prompt_queued") handler(msg as EchoWmFlashPromptQueuedMessage);
    });
  }

  /**
   * Subscribe to "camera_motion_changed" messages only.
   * @returns Unsubscribe function
   */

  onCameraMotionChanged(handler: (message: EchoWmFlashCameraMotionChangedMessage) => void): () => void {
    return this.onMessage((msg) => {
      if (msg.type === "camera_motion_changed") handler(msg as EchoWmFlashCameraMotionChangedMessage);
    });
  }

  /**
   * Subscribe to "rollout_reset_queued" messages only.
   * @returns Unsubscribe function
   */

  onRolloutResetQueued(handler: (message: EchoWmFlashRolloutResetQueuedMessage) => void): () => void {
    return this.onMessage((msg) => {
      if (msg.type === "rollout_reset_queued") handler(msg as EchoWmFlashRolloutResetQueuedMessage);
    });
  }

  /**
   * Subscribe to "chunk_completed" messages only.
   * @returns Unsubscribe function
   */

  onChunkCompleted(handler: (message: EchoWmFlashChunkCompletedMessage) => void): () => void {
    return this.onMessage((msg) => {
      if (msg.type === "chunk_completed") handler(msg as EchoWmFlashChunkCompletedMessage);
    });
  }

  /**
   * Subscribe to "automatic_reset_queued" messages only.
   * @returns Unsubscribe function
   */

  onAutomaticResetQueued(handler: (message: EchoWmFlashAutomaticResetQueuedMessage) => void): () => void {
    return this.onMessage((msg) => {
      if (msg.type === "automatic_reset_queued") handler(msg as EchoWmFlashAutomaticResetQueuedMessage);
    });
  }

  /**
   * Subscribe to the "main_video" recvonly video track the model publishes.
   *
   * The handler fires once the model starts publishing this track; it receives the live MediaStreamTrack and the parent MediaStream (useful for attaching to a `<video>` / `<audio>` element via `srcObject`).
   * @param handler - Called with the received track and its stream
   * @returns Unsubscribe function
   */

  onMainVideo(
    handler: (track: MediaStreamTrack, stream: MediaStream) => void,
  ): () => void {
    const wrapped = (name: string, t: MediaStreamTrack, s: MediaStream) => {
      if (name === "main_video") handler(t, s);
    };
    this.on("trackReceived", wrapped);
    return () => this.off("trackReceived", wrapped);
  }

  /**
   * Subscribe to the "main_audio" recvonly audio track the model publishes.
   *
   * The handler fires once the model starts publishing this track; it receives the live MediaStreamTrack and the parent MediaStream (useful for attaching to a `<video>` / `<audio>` element via `srcObject`).
   * @param handler - Called with the received track and its stream
   * @returns Unsubscribe function
   */

  onMainAudio(
    handler: (track: MediaStreamTrack, stream: MediaStream) => void,
  ): () => void {
    const wrapped = (name: string, t: MediaStreamTrack, s: MediaStream) => {
      if (name === "main_audio") handler(t, s);
    };
    this.on("trackReceived", wrapped);
    return () => this.off("trackReceived", wrapped);
  }
}
